- name: Creo le virtual machine
  hosts: localhost
  connection: local
  vars_prompt:
    - name: "vcenter_host"
      prompt: "Inserisci il nome del vcenter"
      private: no
      default: "uk-vcenter-001.edge.local"
    - name: "vcenter_user"
      prompt: "Inserisci lo username per loggarti al VCENTER"
      private: no
    - name: "vcenter_pass"
      prompt: "Inserisci la password per loggarti al VCENTER"
      private: yes

  tasks:
  - name: Carico in memoria la configurazione
    include_vars:
        file: config.json
        name: configurazione

  - name: stampo la configurazione
    debug: var=configurazione
      

  - name: "Mi assicuro che il clone del template {{  configurazione | json_query('template_cti_scalato') }} venga fatto a macchina spenta"
    vmware_guest:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      name: "{{  configurazione | json_query('template_cti_scalato') }}"
      state: poweredoff
    delegate_to: localhost

  - name: "Mi assicuro che la macchina non sia presente"
    include_tasks: include/elimina_vm.yml
    with_items:
    - "{{  configurazione | json_query('servers[*].name') }}"
   

  - name: "Creo la virtual machine"
    include_tasks: include/crea_vm.yml 
    with_together:
    - "{{  configurazione | json_query('servers[*].name') }}"
    - "{{  configurazione | json_query('servers[*].ip') }}"

  - file: dest=/tmp/.DNS state=absent

  - name: Creo il file con le associazioni DNS
    lineinfile: 
        create: true
        dest: /tmp/.DNS
        state: present
        line: "{{ item.0 }};{{ item.1 }}"
    with_together:
    - "{{  configurazione | json_query('servers[*].name') }}"
    - "{{  configurazione | json_query('servers[*].ip') }}"
    
  - mail:
        subject: '[ANSIBLE] Inserimento nuovi server in DNS'
        to: Martino.Vigano@enghouse.com
        from: ansible@reitek.com
        body: "{{ lookup('file', '/tmp/.DNS') }}"

  - name: creazione degli snapshot iniziali
    vmware_guest_snapshot:
     hostname: "{{ vcenter_host }}"
     username: "{{ vcenter_user }}"
     password: "{{ vcenter_pass }}"
     datacenter: "{{  configurazione | json_query('datacenter') }}"
     folder: "{{  configurazione | json_query('folder') }}"
     name: "{{ item }}"
     state: present
     snapshot_name: DEPLOY
     description: IL Server Appena deployato da template
     validate_certs: false
    with_items:
    - "{{  configurazione | json_query('servers[*].name') }}"
  
  - name: aggiungo i nuovi hosts all'inventory
    add_host:
        name: "{{ item.0 }}"
        ansible_ssh_host: "{{ item.1 }}"
        group: newinstall
    with_together:
    - "{{  configurazione | json_query('servers[*].name') }}"
    - "{{  configurazione | json_query('servers[*].ip') }}"

- name: Operazioni comuni a tutti i server
  hosts: newinstall
  gather_facts: false

  tasks:
  - name: Carico in memoria la configurazione
    include_vars:
        file: config.json
        name: configurazione
  - name: Parto da un server che non ha servizi attivi
    systemd: enabled=false state=stopped name={{ item }}
    with_items:
    - 'opensips.service'
    - 'contact.target'
    - 'crond.service'
    - 'httpd.service'
    - 'msac.service'
    - 'msad@1.service'
    - 'msad@2.service'
    - 'msad@3.service'
    - 'msad@4.service'
    - 'msad@5.service'
    - 'msad@6.service'
    - 'pm2-reicom.service'
    - 'rtpproxy@*.service'
    - 'sems.service'
    - 'tomcat.service'
    - 'slapd.service'
    - 'redis.service'
    - 'rasd.service'
    
  - include_tasks: include/set_ntp_server.yml
    when: "configurazione | json_query('ntp_server')  is defined"
  
  - include_tasks: include/modifica_etichette.yml  
    
  - include_tasks: include/costruisci_hosts.yml
    



